### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by HarryHeights** [RyuzakiKK/NoteCrypt#40]
Hi. I'm Harry. 
I'd like to contribute to your project. I'm a content creator and my I help out mostly by creating documents I feel and think projects should have. Privacy Policy Statements, FAQs, About etc. Mostly anything that has to do with text styled with markdown. 
I think it'll be cool to have a privacy policy statement that will put forward your policies to end users about information collection and use but I'm quite certain you don't collect any user information externally. However, it's still a good thing end users are made aware of this.

I would love to hear your thoughts on this.
Thanks

**Comment by RyuzakiKK** [comment]
Hi Harry.
I'm not an expert in Privacy Policy, so I can't help you much there, but I think it would be fantastic to have one.
With NoteCrypt I don't collect any user data, in fact I don't even ask for the Android Internet permission.
The only required permission is the "write external storage", in order to save and read the notes.

**Comment by HarryHeights** [comment]
I won't say I'm an expert but creating such documents is kind of my thing. You can check my contribution history here on Github. I'll create the document for you and ensure it suits your project.

**Comment by HarryHeights** [comment]
Would you like a FAQs document too? I know notecrypt looks like quite a simple software though. FAQs document might prove helpful to some end users @RyuzakiKK

**Comment by RyuzakiKK** [comment]
Sure, why not.
Do you have already some questions in mind?
I was thinking about something along the line of "Can I organize the notes in different files with different passwords?", "What's the purpose of tags?", "Can I make a manual backup of my notes?", "I'm changing my phone, can I transfer my notes?".

(The answer to the last two question is yes, because I store the encrypted notes inside a folder called `NoteCrypt` in the external memory of the phone. So a user can for example plug the phone in a PC and manually copy the encrypted notes)

**Comment by HarryHeights** [comment]
Yea I have some questions in mind. I'll also add the ones you've mentioned. If there are more you can share so I can merge all our ideas together in one FAQs document.

**Comment by RyuzakiKK** [comment]
Yes just a few more:
"I forgot my password, can I recover my notes?" (no)
"Can you or someone else read my notes?" (no, they are only locally stored and encrypted with the chosen password)
"Can I read my notes on my PC or on iOS?" (no just Android)

**Comment by HarryHeights** [comment]
Great. I'll make up the rest.

**Comment by RyuzakiKK** [comment]
Now available with #41 and #43.
